version: "2"
services:
  jupyterlab-r:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./.jupyter:/home/jovyan/.jupyter
      - ./notebooks:/home/jovyan/notebooks
      - ./datasets:/home/jovyan/datasets
      - ./results:/home/jovyan/results
      - ./plots:/home/jovyan/plots
    command:
      - --no-browser
      - --ip=0.0.0.0
